ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
