<?php

namespace AppBundle\Repository;

/**
 * DateReposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateReposRepository extends \Doctrine\ORM\EntityRepository
{
}
