<?php

namespace AppBundle\Repository;

/**
 * EventCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCustomRepository extends \Doctrine\ORM\EntityRepository
{
	public function eventsAvecTitre(){
		
		
		$qb = $this->createQueryBuilder('e')
		->where(" e.title != 'null'");
		$query = $qb->getQuery(); // return a new Query object
		// get the results of the query
		//dump($results);
		//if ($results) {$retoure=1; }else {$retoure=0;} ;
		
		return $results = $query->getResult(); 
	}
	public function utilisateurEvent($id,$edt)
	{
		$qb = $this->createQueryBuilder('e')
		->where(" e.rdv = $id and e.id =$edt");
		$query = $qb->getQuery(); // return a new Query object
		// get the results of the query
		//dump($results);
		//if ($results) {$retoure=1; }else {$retoure=0;} ;
		
		return $results = $query->getResult(); 
		
	}
}
