<?php

namespace AppBundle\Repository;

/**
 * PlageHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageHoraireRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTypePlage()
	{
		$qb = $this->createQueryBuilder('p');
		$qb->select('p.type')
		->distinct(true);
		$query = $qb->getQuery(); // return a new Query object
		$results = $query->getResult(); // get the results of the query
		return $results;
	}
}
